---
title: "Insert Title"
author: "Insert Names"
date: "Spring 2018"
output: html_document
urlcolor: blue
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final Project

```{r}
#Load libraries
library(readr)
library(rvest)
library(dplyr)
library(ggplot2)
library(caret)

```


We only keep variables relevant to the state and that are not missing for any states.

```{r}
#Upload election integrity dataset
election_integrity <- read_csv("PEI US 2016 state-level (PEI_US_1.0) 16-12-2017.csv")

election_integrity <- election_integrity %>%
  select(stateabbr, PEIIndexi, PEIIndex_rank, PEItype, ratingstate, ratingstate_lci, ratingstate_hci, ratingcountry, ratingcountry_lci, ratingcountry_hci, lawsunfair2, favoredincumbent2, citizens2, lawsi, managed, votinginfo, fairofficials, legalelections, proceduresi, bfavored2, boundariesi, voteregi, oppprevent2, womenopp, minorityopp, leaderselect2, rallies2, partyregi, newspapers, tv2, fairaccess, faircoverage, mediai, donations, rich2, financei, violence2, fraudulent2, easy, choice, postal, expats, internet, rigged2, machinesaccurate, recordssecure, waited2, multiple2, regrestrictive2, popularwill, timely, votingi)

```


```{r}
#Upload voter turnout dataset
voter_turnout <- read_csv("2016 November General Election - Turnout Rates.csv")
voter_turnout <- voter_turnout %>%
  select(State, "VEP.Highest.Office" = "X5", "VAP.Highest.Office" = "X6", "Total.Ballots.Counted.(Estimate)" = "Numerators", "Highest.Office" = "X8", "Voting.Eligible.Population.VEP" = "Denominators", "Voting.Age.Population.VAP" = "X10", "Total.Ineligible.Felons" = "X15", "Abbreviation" = "X17") %>%
  filter(!is.na(State) & State != "United States") %>%
  mutate(Voting.Eligible.Population.VEP = as.numeric(gsub(",", "", as.character(Voting.Eligible.Population.VEP))), Voting.Age.Population.VAP = as.numeric(gsub(",", "", as.character(Voting.Age.Population.VAP))), Total.Ineligible.Felons = as.numeric(gsub(",", "", as.character(Total.Ineligible.Felons)))) %>%
  mutate(Voters.Disenfranchised = Voting.Age.Population.VAP - Voting.Eligible.Population.VEP, Pct.felon.Disenfranchised = Total.Ineligible.Felons / Voting.Age.Population.VAP) %>%
  select(-State)

  
```

```{r}
#Scrape election results dataset
url <- "https://en.wikipedia.org/wiki/United_States_presidential_election,_2016"
tables <- url %>%
  read_html() %>%
  html_nodes(css = "table") 
election_results <- html_table(tables[[38]], fill = TRUE)
names(election_results) <- c("State", "Voting.Type", "Clinton.Number", "Clinton.Percent", "Clinton.Electoral", "Trump.Number", "Trump.Percent", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "Abbreviation")
election_results <- election_results %>%
  select(State, Clinton.Percent, Trump.Percent, Abbreviation) %>%
  filter(State != "U.S. Total", State != "Nebraska, 1st", State != "Nebraska, 2nd", State != "Nebraska, 3rd", State != "Maine, 1st", State != "Maine, 2nd", Clinton.Percent != "%")  %>%
  select(-State)

election_results$Abbreviation[election_results$Abbreviation == "ME–a/l"] <- "ME"
election_results$Abbreviation[election_results$Abbreviation == "NE–a/l"] <- "NE"

election_results <- election_results %>% 
  mutate(Clinton.Percent = as.numeric(sub("%", "", as.character(Clinton.Percent))), Trump.Percent = as.numeric(sub("%", "", as.character(Trump.Percent)))) %>%
  mutate(Vote.Clinton = ifelse(Clinton.Percent - Trump.Percent > 0, "Yes", "No"))

```

note inner_join, left_join, and right_join all do the same thing because we are matching 50 states
```{r}
#Merge datasets
integrity_turnout <- inner_join(election_integrity, voter_turnout, by = c("stateabbr" = "Abbreviation"))
all <- inner_join(integrity_turnout, election_results, by = c("stateabbr" = "Abbreviation"))
```

```{r}
#CW: Experimenting with PCA
pca_test <- all %>%
  select(-stateabbr, -PEIIndexi, -PEIIndex_rank, -PEItype, -ratingstate, -ratingstate_hci, -ratingstate_lci, -ratingcountry, -ratingcountry_lci, -ratingcountry_hci, -lawsi, -proceduresi, -boundariesi, -voteregi, -partyregi, -mediai, -financei, -VEP.Highest.Office, -VAP.Highest.Office, -`Total.Ballots.Counted.(Estimate)`, -Highest.Office, -Voting.Eligible.Population.VEP, -Voting.Age.Population.VAP, -Total.Ineligible.Felons, -Voters.Disenfranchised, -Clinton.Percent, -Trump.Percent, -Vote.Clinton, -votingi, -Pct.felon.Disenfranchised)


prin_comp <- prcomp(pca_test, scale. = T)
biplot(prin_comp, scale = 0)

std_dev <- prin_comp$sdev
pr_var <- std_dev^2
prop_varex <- pr_var/sum(pr_var)
plot(cumsum(prop_varex), xlab = "Principal Component",
              ylab = "Cumulative Proportion of Variance Explained",
              type = "b")

plot(prop_varex, xlab = "Principal Component",
             ylab = "Proportion of Variance Explained",
             type = "b")

cw_data <- data.frame(state = all$stateabbr, index = all$PEIIndexi, clinton = all$Vote.Clinton, pct_dis = all$Pct.felon.Disenfranchised, prin_comp$x) 

ggplot(cw_data, aes(x= index, y=PC1)) +
  geom_point(aes(col = clinton)) 

ggplot(cw_data, aes(x= PC2, y=PC1)) +
  geom_point(aes(col = clinton)) 

#Set cross validation options
cv_opts <- trainControl(method = "repeatedcv", number = 10, repeats = 5)

#Set seed
set.seed(7)

#Build the model
log_model1 <- train(clinton ~ index,  data=cw_data, method="glm", family="binomial",trControl = cv_opts)
log_model2 <- train(clinton ~ index + pct_dis,  data=cw_data, method="glm", family="binomial",trControl = cv_opts)
log_model3 <- train(clinton ~ PC1 + PC2 + PC3 + PC4 + PC5 + PC6 + PC7 + PC8 + PC9 + PC10 + PC11 + PC12 + PC13 +PC14 + PC15 + PC16 + PC17 + PC18 + PC19 + PC20,  data=cw_data, method="glm", family="binomial",trControl = cv_opts)

log_model1
log_model2
log_model3


```

```{r}
#Exploratory Visuals ggplot stuff
ggplot(integrity_turnout, aes(x = Pct.felon.Disenfranchised, y = PEIIndex_rank)) +
  geom_point()
ggplot(all, aes(x = Pct.felon.Disenfranchised, y = PEIIndexi, color = Vote.Clinton)) +
  geom_point()
ggplot(all, aes(x = Percent.Disenfranchised, y = Trump.Percent)) +
  geom_point()
ggplot(all, aes(x = log(Voters.Disenfranchised), y = Clinton.Percent)) +
  geom_point()
ggplot(all, aes(y = log(Voters.Disenfranchised), x = easy)) +
  geom_point()
ggplot(all, aes(y = log(Voters.Disenfranchised), x = votingi)) +
  geom_point()
ggplot(all, aes(y = log(Percent.Disenfranchised), x = reglisted)) +
  geom_point()
ggplot(all, aes(y = log(Voters.Disenfranchised), x = ineligible)) +
  geom_point()
ggplot(all, aes(y = Clinton.Percent, x = ineligible)) +
  geom_point()
```






